name: Docker Build and Publish

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual supplied image tag like 1.16.0'
        required: true
        type: string
  push:
    tags:
      - "*.*.*"
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/mapproxy/mapproxy/mapproxy
          tags: |
            type=semver,pattern={{version}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v4
        if: ${{ inputs.tags }}
        with:
          context: docker/
          file: ./docker/Dockerfile
          push: true
          build-args: |
            MAPPROXY_VERSION=${{ inputs.tags }}
          target: base
          tags: |
            ghcr.io/mapproxy/mapproxy/mapproxy:${{ inputs.tags }}

      - name: Build and push base image
        uses: docker/build-push-action@v4
        if: ${{ !inputs.tags }}
        with:
          context: docker/
          file: ./docker/Dockerfile
          push: true
          build-args: |
            MAPPROXY_VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          target: base
          tags: |
            ghcr.io/mapproxy/mapproxy/mapproxy:${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}

      - name: Build and push development image
        uses: docker/build-push-action@v4
        if: ${{ inputs.tags }}
        with:
          context: docker/
          file: ./docker/Dockerfile
          push: true
          build-args: |
            MAPPROXY_VERSION=${{ inputs.tags }}
          target: development
          tags: |
            ghcr.io/mapproxy/mapproxy/mapproxy:${{ inputs.tags }}-dev

      - name: Build and push development image
        uses: docker/build-push-action@v4
        if: ${{ !inputs.tags }}
        with:
          context: docker/
          file: ./docker/Dockerfile
          push: true
          build-args: |
            MAPPROXY_VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          target: development
          tags: |
            ghcr.io/mapproxy/mapproxy/mapproxy:${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}-dev

      - name: Build and push nginx image
        uses: docker/build-push-action@v4
        if: ${{ inputs.tags }}
        with:
          context: docker/
          file: ./docker/Dockerfile
          push: true
          build-args: |
            MAPPROXY_VERSION=${{ inputs.tags }}
          target: nginx
          tags: |
            ghcr.io/mapproxy/mapproxy/mapproxy:${{ inputs.tags }}-nginx
      - name: Build and push nginx image
        uses: docker/build-push-action@v4
        if: ${{ !inputs.tags }}
        with:
          context: docker/
          file: ./docker/Dockerfile
          push: true
          build-args: |
            MAPPROXY_VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          target: nginx
          tags: |
            ghcr.io/mapproxy/mapproxy/mapproxy:${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}-nginx
