name: Docker Build and Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/mapproxy/mapproxy/mapproxy
          tags: |
            type=semver,pattern={{version}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v4
        with:
          context: docker/
          file: ./docker/Dockerfile
          push: true
          build-args: |
            MAPPROXY_VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          target: base
          tags: |
            ${{ steps.meta.outputs.tags }}

      - name: Build and push development image
        uses: docker/build-push-action@v4
        with:
          context: docker/
          file: ./docker/Dockerfile
          push: true
          build-args: |
            MAPPROXY_VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          target: development
          tags: |
            ${{ steps.meta.outputs.tags }}-dev

      - name: Build and push nginx image
        uses: docker/build-push-action@v4
        with:
          context: docker/
          file: ./docker/Dockerfile
          push: true
          build-args: |
            MAPPROXY_VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          target: nginx
          tags: |
            ${{ steps.meta.outputs.tags }}-nginx
